<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Main page</title>
</head>
<body>
<h2>${phrase}</h2>
<form action="/">
    <input type="radio" name="choice" value="education">Образование
    <input type="radio" name="choice" value="personal_grow">Личное развитие
    <input type="radio" name="choice" value="relation">Отношения
    <input type="radio" name="choice" value="history">История
    <input type="submit" value="Получить">
</form>
</body>
</html>